/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swc.microservice.complaint

import swc.microservice.complaint.drivers.DatabaseManager

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val dbManager = DatabaseManager()
}
