/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swc.microservice.complaint

import swc.microservice.complaint.drivers.DatabaseManager
import swc.microservice.complaint.entities.Complaint
import swc.microservice.complaint.entities.ComplaintStatus
import swc.microservice.complaint.entities.Issuer
import swc.microservice.complaint.usecases.createComplaint

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val dbManager = DatabaseManager()
    createComplaint(Complaint("", "", "", Issuer.USER, "", ComplaintStatus.OPEN), dbManager)
}
